version: 0.2
phases:
  install:
    commands:
      - |
        #Update
        apt-get update
        # Install SQLITE3
        apt-get install -y sqlite3
        apt-get install php-sqlite3
        #Install composer
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php ;
        php -r "unlink('composer-setup.php');" ;
        mv composer.phar /usr/local/bin/composer
  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer deps
      - composer install
      - touch database/database.sqlite
      - php artisan migrate --database=sqlite --force

  post_build:
    commands:
      - echo Build completed on `date`
      - ./vendor/bin/phpunit