version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      # Install laravel packages
      - composer -q update
      - composer -q install
      - apt-get -qq update -y

      # NPM install
      - apt-get -qq install nodejs-dev node-gyp libssl1.0-dev
      - apt-get -qq install nodejs npm
      - npm i --silent

      # Start Mysql for unit tests
      - apt-get -qq install -y mysql-server
      - su mysql -s /bin/bash -c "/usr/sbin/mysqld" &
      - add-apt-repository ppa:ondrej/php
      - apt-get -qq update -y
      - apt install php7.3-mysql -y
      - service mysql start

  post_build:
    commands:
      # Create test DB
      - /usr/bin/mysql  -u root -e "CREATE USER 'admin'@'127.0.0.1' IDENTIFIED BY ''"
      - /usr/bin/mysql  -u root -e "FLUSH PRIVILEGES"
      - /usr/bin/mysql  -u root -e "CREATE DATABASE test"
      - /usr/bin/mysql  -u root -e "GRANT ALL ON *.* TO 'admin'@'127.0.0.1' IDENTIFIED BY '' WITH GRANT OPTION"

      # Run Tests
      - ./vendor/bin/phpunit

      # Make deploy hook executable
      - chmod +x .platform/hooks/postdeploy/01_set_envs.sh

artifacts:
  discard-paths: no
  files:
    '**/*'